export const luckyBlockDiceSecureAbi = [
  {
    type: "function",
    name: "PLAY_FEE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "totalPlays",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "scores",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "commits",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "commit",
    stateMutability: "nonpayable",
    inputs: [{ name: "hash", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "play",
    stateMutability: "payable",
    inputs: [{ name: "seed", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "contractBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "Committed",
    inputs: [{ indexed: true, name: "player", type: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Played",
    inputs: [
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "dice", type: "uint256" },
      { indexed: false, name: "win", type: "bool" },
    ],
    anonymous: false,
  },
] as const;
